### ISSUE TITLE
Codestyle

### ISSUE THREAD

**Issue by alexmikhalevich** [regu1yar/Strategy#4]
Хорошей практикой является делать поля класса приватными или, в особых случаях, защищенными. https://github.com/regu1yar/Strategy/blob/0285de094cafa0511574ee8f0c86e22c38f100b4/Units/HumanUnits.hpp#L37

**Comment by regu1yar** [comment]
Эти статические поля используется для тестирования корректного создания юнитов. Чтобы сделать их private или protected, потребуется написать много get'теров или сделать тесты менее гибкими для изменения начальных значений. Не знаю, как по-другому выйти из этой ситуации. К тому же они const и не меняются на протяжении всей работы, поэтому не вижу проблем в том, чтобы они были публичными.

**Comment by maked0n** [comment]
> Эти статические поля используется для тестирования корректного создания юнитов
я правильно понял, что эти поля нужны только для тестового кода?

**Comment by regu1yar** [comment]
Для тестирования и для создания юнитов с указанными в этих полях начальными значениями.
